easy_admin:
    site_name: 'Ati-News'

    design: 
           brand_color: '#81b9ba'
           assets:
                  css: ['css/backend.css']

    entities:
        Actualite:
            class: App\Entity\Actualite
            list:
                fields: ['id', 'titre', 'date', 'image', 'description']
        User:
            class: App\Entity\User
            list:
                fields: ['id', 'nom', 'prenom', 'email', 'password', 'image','roles']

        Admin:
          class: App\Entity\Admin
                
                

     
           
