easy_admin:
    site_name: 'Ati-News'

    design: 
           brand_color: '#81b9ba'
           assets:
                  css: ['css/backend.css']

    entities:
        Actualite:
            class: App\Entity\Actualite
            list:
                fields: ['id', 'Titre', 'Date', 'Image', 'Description']
        User:
            class: App\Entity\User
            list:
                fields: ['id', 'Nom', 'Prenom', 'E-mail', 'Mot de passe', 'Image','']   
                
                

     
           
      