fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\Admin
    from_email:
        address: "todo"
        sender_name: "todo"
          #registration:
          #form:
        #type: App\Form\RegistrationType
