vich_uploader:
    db_driver: orm

    mappings:
        actualite_images:
            uri_prefix:  '%app.path.actualite_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.actualite_images%'
